config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  # oauth authorization routes
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/google_oauth2', as: :google_login
  get '/logout', to: 'sessions#destroy', as: :google_logout

  # user profile routes
  get '/profile', to: 'profile#show', as: :profile
  get '/profile/edit', to: 'profile#edit', as: :profile_edit
  patch '/profile', to: 'profile#update', as: :profile_update

  # friends routes
  get 'friends/all', to: 'friends#all', as: :friends_all
  resources :friends, only: [:index, :create]

  # groups routes
  get 'groups/all', to: 'groups#all', as: :groups_all
  resources :groups, only: [:index, :new, :create, :show]

  # discover routes
  get '/discover/random', to: 'discover#random', as: :discover_random
  get '/discover/swipe', to: 'discover#swipe', as: :swipe
  resources :discover, only: [:index, :show]

  # admin routes
  get '/admin/refresh_availability', to: 'admin#refresh_availability', as: :refresh_availability
  get '/admin/update_movie_details', to: 'admin#update_movie_details', as: :update_details
  resources :admin, only: [:index]

  # movie routes
  resources :movies, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index

  end

  def refresh_availability
    refresh = AdminFacade.refresh_service_availability(params[:service])

    redirect_to admin_index_path, notice: "#{refresh.service_name} has been updated and currently has #{refresh.movie_count} movies available."
  end

  def update_movie_details
    update = AdminFacade.update_movie_details
    output = "#{update.movie_count} movies updated. Update status: #{update.status}"

    redirect_to admin_index_path, notice: output
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def authenticate
    unless user_signed_in?
      redirect_to root_path, notice: "You must be logged in to perform that action. Click 'Log In' to log in or create an account."
    end
  end

  def current_user
    @current_user ||= CurrentUser.new(session[:current_user]) if session[:current_user]
  end

  def user_signed_in?
    !!current_user
  end
end

app/controllers/discover_controller.rb
class DiscoverController < ApplicationController
  before_action :authenticate

  def index

  end

  def show

  end

  def random
    @movie = DiscoverFacade.find_random_movie(current_user.id)
    @filter = {random: true}

    render :show
  end

  def swipe
    swipe = BackendService.create_swipe(swipe_params.merge(user_id: current_user.id))

    if params[:random] = true
      redirect_to discover_random_path
    else
      # future iteration
    end
  end

  private

  def swipe_params
    params.permit(:rating, :movie_id)
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :authenticate

  def index
    @friends = UserFacade.top_three_friends(current_user.id)
  end

  def create
    friend = UserFacade.add_friend(current_user.id, params[:email])

    if friend.is_a?(String)
      redirect_to friends_path, notice: friend
    else
      redirect_to friends_path, notice: "#{friend.first_name} #{friend.last_name} has been added to friends list."
    end
  end

  def all
    @friends = UserFacade.all_friends(current_user.id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate

  def index
    @groups = GroupFacade.top_three_groups(current_user.id)
  end

  def show
    @group = GroupFacade.find_group(params[:id])
    @matches = GroupFacade.find_matches(params[:id])
  end

  def all
    @groups = GroupFacade.all_groups(current_user.id)
  end

  def new
    @friends = UserFacade.all_friends(current_user.id)
  end

  def create
    user_ids = user_ids(params)
    group = GroupFacade.make_group(user_ids, group_params[:name])

    redirect_to "/groups/#{group.id}", notice: "#{group.name} was successfully created."
  end

  private

  def user_ids(params)
    friends = params.select do |key, value|
      value == "1"
    end
    ids = friends.keys.map do |id|
      id.to_i
    end
    ids << current_user.id
  end

  def group_params
    params.permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate

  def show
    @movie = MovieFacade.find_movie(params[:id])
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :authenticate

  def show

  end

  def edit

  end

  def update
    uid = current_user.uid
    session[:current_user] = UserFacade.update_existing_user(user_params, uid)

    redirect_to profile_path, notice: 'Your profile information has been updated.'
  end

  private

  def user_params
    params.permit(:first_name, :last_name, :email, :image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = UserFacade.find_or_create_user(user_params)
    session[:current_user] = user

    redirect_to root_path, notice: "Welcome, #{user.first_name}!"
  end

  def destroy
    session.clear

    redirect_to root_path, notice: 'You are now logged out.'
  end

  protected

  def user_params
    auth_hash = request.env['omniauth.auth']
    {
      uid: auth_hash[:uid],
      email: auth_hash[:info][:email],
      first_name: auth_hash[:info][:first_name],
      last_name: auth_hash[:info][:last_name],
      image: auth_hash[:info][:image]
    }
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index.html.erb
<div class="admin-marquee">
  <%= image_tag('pof_admin_link.png', height: 150) %>
</div>

<div class="admin-form">
  <h3>Service Refresh Form</h3>
  <p>Services constantly change what movies they offer.<br>Select a service and click 'Refresh Availability' to update a service's movie availabilities</p>
  <%= form_with(url: refresh_availability_path, method: :get) do |f| %>
    <div id='netflix-radio'><%= f.radio_button :service, 'netflix' %>Netflix</div>
    <div id='hulu-radio'><%= f.radio_button :service, 'hulu' %>Hulu</div>
    <div id='amazon-radio'><%= f.radio_button :service, 'amazon' %>Amazon Prime Video</div><br>

    <%= submit_tag("Refresh Availability") %>
  <% end %>
</div>

<div class="admin-form">
  <h3>Update Movie Details</h3>
  <p>After submitting the 'Service Refresh Form' above, use this button to fully populate all newly added movies with relevant information.</p>
  <%= button_to 'Update Movie Details', '/admin/update_movie_details', method: :get %>
</div>

app/views/discover/index.html.erb
<div class="discover-marquee">
  <%= image_tag('pof_discover_link.png', height: 150) %>
</div>

<div class="discover-description">
  <h1>Discover Movies</h1>
  <h4>Let's find you some movies to watch! Fill out the form below, and click submit to filter out the movies we suggest. Or, click 'No Filters' to start swiping random available movies.</h4>
  <%= button_to 'No Filters', discover_random_path, method: :get %>
</div>

app/views/discover/show.html.erb
<div class="discover-marquee">
  <%= image_tag('pof_discover_link.png', height: 150) %>
</div>

<div class="movie-display">
  <div class="movie-title">
    <h1 id='movie-title'><%= @movie.title %> (<%= @movie.year %>)</h1>
  </div>

  <div class="movie-info">
    <div class="movie-poster">
      <% if @movie.poster_path %>
        <%= image_tag("https://image.tmdb.org/t/p/w300/" + @movie.poster_path) %>
      <% end %>
    </div>

    <div class="movie-details">
      <div class="movie-genres">
        <% if @movie.genres %>
          <h3 id='movie-header'>
            Genres:
          </h3>
          <h4>
            <% @movie.genres.each do |genre| %>
              <%= genre %><%= ', ' unless genre == @movie.genres.last %>
            <% end %>
          </h4>
        <% end %>
      </div>


      <div class="movie-rating">
        <h3 id='movie-header'>Rating:</h3>
        <h4>
          <% if @movie.vote_average %>
            <%= @movie.vote_average %>/10
          <% else %>
            --/10
          <% end %><br>
          <% if @movie.vote_count %>
            <%= @movie.vote_count %>
          <% else %>
            0
          <% end %>
          Total Votes
        </h4>
      </div>
      <div class="movie-description">
        <h3 id='movie-header'>Description:</h3>
        <h4><%= @movie.description %></h4>
      </div>
    </div>
  </div>
</div>

<div class="swipe-links">
  <div class="swipe-left-link">
    <%= link_to image_tag('no_icon.png', size:200, class: 'swipe-link'), swipe_path(@filter.merge(movie_id: @movie.id, rating: 0)) %>
  </div>

  <div class="swipe-prompt">
    <h2>Want to<br>Watch it?</h2>
  </div>

  <div class="swipe-right-link">
    <%= link_to image_tag('yes_icon.png', size:200, class: 'swipe-link'), swipe_path(@filter.merge(movie_id: @movie.id, rating: 1)) %>
  </div>
</div>

app/views/friends/all.html.erb
<div class="friends-marquee">
  <%= image_tag('pof_friends_link.png', height: 150) %>
</div>

<div class="friends-section">
  <% if @friends != [] %>
    <h2>All Friends</h2>
    <% @friends.each_slice(4) do |friend_slice| %>
      <div class="friendslist">
        <% friend_slice.each do |friend| %>
          <div class="friend-info">
            <h3><%= "#{friend.first_name} #{friend.last_name}" %></h3>
            <h4><%= friend.email %></h4>
            <%= image_tag friend.image, height: 80 %>
          </div>
        <% end %>
      </div>
      <br><br>
    <% end %>
  <% else %>
    <h4>You currently have no friends :(</h4>
  <% end %>
</div>

<div class="friends-section">
  <h2>Add a Friend</h2>
  <h4>
    Enter a registered user's email below to add them as your friend.
  </h4>
  <div class="friends-creation">
    <%= form_with(url: friends_path, method: :post) do |f| %>
      <h3><%= f.label('Email') %>
      <%= f.text_field :email %></h3>

      <%= submit_tag("Add Friend") %>
    <% end %>
  </div>
</div>

app/views/friends/index.html.erb
<div class="friends-marquee">
  <%= image_tag('pof_friends_link.png', height: 150) %>
</div>

<div class="friends-section">
  <% if @friends != [] %>
    <h1>Your Friends</h1>
    <div class="friendslist">
      <% @friends.each do |friend| %>
        <div class="friend-info">
          <h3><%= "#{friend.first_name} #{friend.last_name}" %></h3>
          <h4><%= friend.email %></h4>
          <%= image_tag friend.image, height: 80 %>
        </div>
      <% end %>
    </div>
    <br>
    <%= link_to 'View All Friends', '/friends/all' %>
    <br><br>
  <% else %>
    <h4>You currently have no friends :(</h4>
  <% end %>
</div>

<div class="friends-section">
  <h1>Add a Friend</h1>
  <h4>
    Enter a registered user's email below to add them as your friend.
  </h4>
  <div class="friends-creation">
    <%= form_with(url: friends_path, method: :post) do |f| %>
      <h4><%= f.label('Email') %>
      <%= f.text_field :email %></h4>

      <%= submit_tag("Add Friend") %>
    <% end %>
  </div>
</div>

app/views/groups/all.html.erb
<div class="groups-marquee">
  <%= image_tag('pof_groups_link.png', height: 150) %>
</div>

<div class="groups-section">
  <% if @groups != [] %>
    <h1>All Groups</h1>
    <% @groups.each_slice(4) do |group_slice| %>
      <div class="groupslist">
        <% group_slice.each do |group| %>
          <div class="group-info">
            <h3><%= link_to("#{group.name}", group_path(group.id)) %></h3>
            <h4>Members:</h4>
            <% group.users.each do |user| %>
              <p><%= "#{user.first_name} #{user.last_name}" %></p>
            <% end %>
          </div>
        <% end %>
      </div>
      <br><br>
    <% end %>
  <% else %>
    <h4>You currently have no groups :(</h4>
  <% end %>

  <%= link_to 'Create a New Group', '/groups/new' %>
</div>

app/views/groups/index.html.erb
<div class="groups-marquee">
  <%= image_tag('pof_groups_link.png', height: 150) %>
</div>

<div class="groups-section">
  <% if @groups != [] %>
    <h1>Your Groups</h1>
    <div class="groupslist">
      <% @groups.each do |group| %>
        <div class="group-info">
          <h3><%= link_to("#{group.name}", group_path(group.id)) %></h3>
          <h4>Members:</h4>
          <% group.users.each do |user| %>
            <p><%= "#{user.first_name} #{user.last_name}" %></p>
          <% end %>
        </div>
      <% end %>
    </div>
    <br>
    <%= link_to 'View All Groups', groups_all_path %>
    <br><br>
  <% else %>
    <h4>You currently have no groups :(</h4>
  <% end %>

  <%= link_to 'Create a New Group', '/groups/new' %>
</div>

app/views/groups/new.html.erb
<div class="groups-marquee">
  <%= image_tag('pof_groups_link.png', height: 150) %>
</div>

<div class="groups-section">
  <h1>Create a Group</h1>
  <h4>
    Enter a name for the group and the friends you'd like to add.
  </h4>
  <div class="groups-creation">
    <%= form_with(url: groups_path, method: :post) do |f| %>
      <div class="group-friends">
        <h4>
          <%= f.label('Name:') %>
          <%= f.text_field :name %>
        </h4>
        <% @friends.each_slice(4) do |friend_slice| %>
          <div class="group-slice">
            <% friend_slice.each do |friend| %>
              <div class="group-check-box">
                <h4>
                  <%= f.label("friend_#{friend.id}", "#{friend.first_name} #{friend.last_name}") %>
                  <%= f.check_box friend.id.to_s.to_sym %>
                </h4>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
      <%= submit_tag("Create Group") %>
    <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<div class="groups-marquee">
  <%= image_tag('pof_groups_link.png', height: 150) %>
</div>

<div class="groups-section">
  <h1><%= @group.name %></h1>
  <h2>Members:</h2>
  <% @group.users.each_slice(3) do |user_slice| %>
    <div class="groupslist">
      <% user_slice.each do |user| %>
        <div class="friend-info">
          <h4><%= "#{user.first_name} #{user.last_name}" %></h4>
          <p><%= user.email %></p>
          <%= image_tag user.image, height: 80 %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<div class="matches-section">
  <h2>Movie Matches for <%= @group.name %></h2>
  <% @matches.each_slice(4) do |match_slice| %>
    <div class="matchlist">
      <% match_slice.each do |match| %>
        <div class="match-info">
        <h4><%= link_to "#{match.title} (#{match.year})", movie_path(match.id) %></h4>
          <% if match.poster_path %>
            <%= image_tag("https://image.tmdb.org/t/p/w200/" + match.poster_path) %>
          <% end %>
          <% if match.genres %>
            <h4>
              Genres:<br>
            </h4>
            <p>
              <% match.genres.each do |genre| %>
                <%= genre %><%= ', ' unless genre == match.genres.last %>
              <% end %>
            </p>
          <% end %>
          <p><%= "Average Rating: #{match.vote_average}/10" %></p>
          <p><%= "#{match.vote_count} Total Reviews" %></p>
          <h4>Currently Available On:</h4>
          <% if match.services %>
            <% match.services.each do |service| %>
              <%= image_tag(service.logo, height: 70) %>
            <% end %>
          <% else %>
            <p>Not currently available on Netflix, Hulu, or Amazon Prime Video :(</p>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlentyOfFlicksFe</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class = "topnav">
      <div class="home-link">
        <%= link_to image_tag('pof_home_link.png', width:120), root_path %>
      </div>
      <% if current_user %>
        <div class="profile-link">
          <%= link_to image_tag('pof_profile_link.png', width:120), profile_path %>
        </div>
        <div class="discover-link">
          <%= link_to image_tag('pof_discover_link.png', width:120), discover_index_path %>
        </div>
        <div class="friends-link">
          <%= link_to image_tag('pof_friends_link.png', width:120), friends_path %>
        </div>
        <div class="groups-link">
          <%= link_to image_tag('pof_groups_link.png', width:120), groups_path %>
        </div>
        <div class="log-out">
          <%= link_to image_tag('pof_log_out_link.png', width:120), google_logout_path %>
        </div>
      <% else %>
      <div class="log-in">
        <%= link_to image_tag('pof_log_in_link.png', width:120), google_login_path %>
      </div>
      <% end %>
    </nav>
      <% flash.each do |name, msg| %>
        <div class="flash-messages">
          <div class= "<%=name%>-flash">
            <p1><%= msg %></p1>
          </div>
        </div>
      <% end %>
      <%= yield %>
  </body>
</html>

app/views/movies/show.html.erb
<div class="discover-marquee">
  <%= image_tag('pof_discover_link.png', height: 150) %>
</div>

<div class="movie-display">
  <div class="movie-title">
    <h1 id='movie-title'><%= @movie.title %> (<%= @movie.year %>)</h1>
  </div>

  <div class="movie-info">
    <div class="movie-poster">
      <% if @movie.poster_path %>
        <%= image_tag("https://image.tmdb.org/t/p/w300/" + @movie.poster_path) %>
      <% end %>
    </div>

    <div class="movie-details">
      <div class="movie-genres">
        <% if @movie.genres %>
          <h3>
            Genres:<br>
          </h3>
          <h4>
            <% @movie.genres.each do |genre| %>
              <%= genre %><%= ', ' unless genre == @movie.genres.last %>
            <% end %>
          </h4>
        <% end %>
      </div>

      <div class="movie-rating">
        <h3>Rating:</h3>
        <h4>
          <% if @movie.vote_average %>
            <%= @movie.vote_average %>/10
          <% else %>
            --/10
          <% end %><br>
          <% if @movie.vote_count %>
            <%= @movie.vote_count %>
          <% else %>
            0
          <% end %>
          Total Votes
        </h4>
      </div>
      <div class="movie-description">
        <h3>Description:</h3>
        <h4><%= @movie.description %></h4>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="pof-marquee">
  <%= image_tag('pof_marquee.png', height: 250) %>
</div>

<div class="app-description">
  <h3 id='description-opener'>We all know the struggle.</h3>
  <div class="app-problem">
    <h4>
      You sit down to watch a movie with a group of friends or significant other, and spend more time picking out a suitable flick than actually watching the movie.
    </h4>
  </div>
  <div class="enter-pof">
    <div class="enter-pof-logo">
      <%= image_tag 'plenty_of_flicks_logo.png', width: 150 %>
    </div>
    <h1 id='enter-pof-text'>Enter<br>Plenty of Flicks</h1>
    <div class="enter-pof-logo">
      <%= image_tag 'plenty_of_flicks_logo.png', width: 150 %>
    </div>
  </div>
</div>
<div class="app-description">
  <div class="app-instructions">
    <h3 id='instruction-opener'>How it Works:</h3>
    <h4>
      <div id="instruction-step">
        Step #1:
      </div>
      <% if current_user %>
        Log in with google.
      <% else %>
        <%= link_to 'Log in with google', google_login_path %>.
      <% end %>
    </h4>
    <h4>
      <div id="instruction-step">
        Step #2:
      </div>
      Click <%= link_to 'Movies', discover_index_path %> to cycle through available movies.<br><br>
      <div id="instruction-step">
        Step #3:
      </div>
      As you're cycling through movies, click one of the icons below to either add movies to your watchlist or remove them from your discover pool.
      <div class="no-yes-icons">
        <div class="yes-icon-info">
          <%= image_tag('yes_icon.png', width: 70) %>
        </div>
        <div class="no-or-yes">
          or
        </div>
        <div class="no-icon-info">
          <%= image_tag('no_icon.png', width: 70) %>
        </div>
      </div>
    </h4>
    <h4>
      <div id="instruction-step">
        Step #4:
      </div>
      Invite your friends to join the app, and click <%= link_to 'Friends', friends_path %> to add them to your friendslist.
    </h4>
    <h4>
      <div id="instruction-step">
        Step #5:
      </div>
      When it's time to watch a movie, click <%= link_to 'Groups', groups_path %> to make a group with the friends you'll be watching with. We'll give you a list of flicks that you ALL want to watch, and information about where you can watch them.
    </h4>
  </div>
</div>